// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message/message.proto

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SockObj_ObjType int32

const (
	SockObj_FILE   SockObj_ObjType = 0
	SockObj_STRING SockObj_ObjType = 1
	SockObj_CLOSE  SockObj_ObjType = 2
)

var SockObj_ObjType_name = map[int32]string{
	0: "FILE",
	1: "STRING",
	2: "CLOSE",
}
var SockObj_ObjType_value = map[string]int32{
	"FILE":   0,
	"STRING": 1,
	"CLOSE":  2,
}

func (x SockObj_ObjType) String() string {
	return proto.EnumName(SockObj_ObjType_name, int32(x))
}
func (SockObj_ObjType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_message_0f61c5ebec88e27f, []int{0, 0}
}

type SockObj struct {
	ObjType              SockObj_ObjType  `protobuf:"varint,1,opt,name=objType,proto3,enum=message.SockObj_ObjType" json:"objType,omitempty"`
	FileObj              *SockObj_FileObj `protobuf:"bytes,2,opt,name=file_obj,json=fileObj,proto3" json:"file_obj,omitempty"`
	StrObj               *SockObj_StrObj  `protobuf:"bytes,3,opt,name=str_obj,json=strObj,proto3" json:"str_obj,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SockObj) Reset()         { *m = SockObj{} }
func (m *SockObj) String() string { return proto.CompactTextString(m) }
func (*SockObj) ProtoMessage()    {}
func (*SockObj) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_0f61c5ebec88e27f, []int{0}
}
func (m *SockObj) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SockObj.Unmarshal(m, b)
}
func (m *SockObj) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SockObj.Marshal(b, m, deterministic)
}
func (dst *SockObj) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SockObj.Merge(dst, src)
}
func (m *SockObj) XXX_Size() int {
	return xxx_messageInfo_SockObj.Size(m)
}
func (m *SockObj) XXX_DiscardUnknown() {
	xxx_messageInfo_SockObj.DiscardUnknown(m)
}

var xxx_messageInfo_SockObj proto.InternalMessageInfo

func (m *SockObj) GetObjType() SockObj_ObjType {
	if m != nil {
		return m.ObjType
	}
	return SockObj_FILE
}

func (m *SockObj) GetFileObj() *SockObj_FileObj {
	if m != nil {
		return m.FileObj
	}
	return nil
}

func (m *SockObj) GetStrObj() *SockObj_StrObj {
	if m != nil {
		return m.StrObj
	}
	return nil
}

type SockObj_FileObj struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Len                  int64    `protobuf:"varint,2,opt,name=len,proto3" json:"len,omitempty"`
	Md5                  string   `protobuf:"bytes,3,opt,name=md5,proto3" json:"md5,omitempty"`
	Last                 bool     `protobuf:"varint,4,opt,name=last,proto3" json:"last,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SockObj_FileObj) Reset()         { *m = SockObj_FileObj{} }
func (m *SockObj_FileObj) String() string { return proto.CompactTextString(m) }
func (*SockObj_FileObj) ProtoMessage()    {}
func (*SockObj_FileObj) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_0f61c5ebec88e27f, []int{0, 0}
}
func (m *SockObj_FileObj) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SockObj_FileObj.Unmarshal(m, b)
}
func (m *SockObj_FileObj) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SockObj_FileObj.Marshal(b, m, deterministic)
}
func (dst *SockObj_FileObj) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SockObj_FileObj.Merge(dst, src)
}
func (m *SockObj_FileObj) XXX_Size() int {
	return xxx_messageInfo_SockObj_FileObj.Size(m)
}
func (m *SockObj_FileObj) XXX_DiscardUnknown() {
	xxx_messageInfo_SockObj_FileObj.DiscardUnknown(m)
}

var xxx_messageInfo_SockObj_FileObj proto.InternalMessageInfo

func (m *SockObj_FileObj) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *SockObj_FileObj) GetLen() int64 {
	if m != nil {
		return m.Len
	}
	return 0
}

func (m *SockObj_FileObj) GetMd5() string {
	if m != nil {
		return m.Md5
	}
	return ""
}

func (m *SockObj_FileObj) GetLast() bool {
	if m != nil {
		return m.Last
	}
	return false
}

func (m *SockObj_FileObj) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SockObj_StrObj struct {
	Val                  string   `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	System               bool     `protobuf:"varint,2,opt,name=system,proto3" json:"system,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SockObj_StrObj) Reset()         { *m = SockObj_StrObj{} }
func (m *SockObj_StrObj) String() string { return proto.CompactTextString(m) }
func (*SockObj_StrObj) ProtoMessage()    {}
func (*SockObj_StrObj) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_0f61c5ebec88e27f, []int{0, 1}
}
func (m *SockObj_StrObj) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SockObj_StrObj.Unmarshal(m, b)
}
func (m *SockObj_StrObj) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SockObj_StrObj.Marshal(b, m, deterministic)
}
func (dst *SockObj_StrObj) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SockObj_StrObj.Merge(dst, src)
}
func (m *SockObj_StrObj) XXX_Size() int {
	return xxx_messageInfo_SockObj_StrObj.Size(m)
}
func (m *SockObj_StrObj) XXX_DiscardUnknown() {
	xxx_messageInfo_SockObj_StrObj.DiscardUnknown(m)
}

var xxx_messageInfo_SockObj_StrObj proto.InternalMessageInfo

func (m *SockObj_StrObj) GetVal() string {
	if m != nil {
		return m.Val
	}
	return ""
}

func (m *SockObj_StrObj) GetSystem() bool {
	if m != nil {
		return m.System
	}
	return false
}

func init() {
	proto.RegisterType((*SockObj)(nil), "message.SockObj")
	proto.RegisterType((*SockObj_FileObj)(nil), "message.SockObj.FileObj")
	proto.RegisterType((*SockObj_StrObj)(nil), "message.SockObj.StrObj")
	proto.RegisterEnum("message.SockObj_ObjType", SockObj_ObjType_name, SockObj_ObjType_value)
}

func init() { proto.RegisterFile("message/message.proto", fileDescriptor_message_0f61c5ebec88e27f) }

var fileDescriptor_message_0f61c5ebec88e27f = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4d, 0x6b, 0xb3, 0x40,
	0x10, 0x80, 0x5f, 0xf3, 0xe1, 0xea, 0xbc, 0xa5, 0xc8, 0x40, 0xdb, 0x25, 0x27, 0xc9, 0x49, 0x7a,
	0xb0, 0xc5, 0xd0, 0x5f, 0x50, 0x92, 0x12, 0x08, 0x15, 0xd6, 0xdc, 0x8b, 0xa6, 0x9b, 0x12, 0xab,
	0x6e, 0x70, 0x97, 0x42, 0x7e, 0x78, 0xef, 0x65, 0xc7, 0xf5, 0xd4, 0x9e, 0xe6, 0x99, 0x71, 0x9e,
	0x99, 0xc1, 0x85, 0x9b, 0x56, 0x6a, 0x5d, 0x7e, 0xc8, 0x07, 0x17, 0xd3, 0x73, 0xaf, 0x8c, 0x42,
	0xe6, 0xd2, 0xe5, 0xf7, 0x04, 0x58, 0xa1, 0x0e, 0x9f, 0x79, 0x55, 0x63, 0x06, 0x4c, 0x55, 0xf5,
	0xfe, 0x72, 0x96, 0xdc, 0x8b, 0xbd, 0xe4, 0x3a, 0xe3, 0xe9, 0x68, 0xb9, 0x96, 0x34, 0x1f, 0xbe,
	0x8b, 0xb1, 0x11, 0x57, 0x10, 0x1c, 0x4f, 0x8d, 0x7c, 0x53, 0x55, 0xcd, 0x27, 0xb1, 0x97, 0xfc,
	0xff, 0x43, 0xda, 0x9c, 0x1a, 0x99, 0x57, 0xb5, 0x60, 0xc7, 0x01, 0xf0, 0x11, 0x98, 0x36, 0x3d,
	0x39, 0x53, 0x72, 0xee, 0x7e, 0x39, 0x85, 0xe9, 0xad, 0xe2, 0x6b, 0x8a, 0x0b, 0x05, 0xcc, 0x4d,
	0x41, 0x0e, 0xec, 0xa0, 0x3a, 0x23, 0x3b, 0x43, 0x57, 0x5e, 0x89, 0x31, 0xc5, 0x08, 0xa6, 0x8d,
	0xec, 0xe8, 0x8c, 0xa9, 0xb0, 0x68, 0x2b, 0xed, 0xfb, 0x13, 0x2d, 0x09, 0x85, 0x45, 0x44, 0x98,
	0x35, 0xa5, 0x36, 0x7c, 0x16, 0x7b, 0x49, 0x20, 0x88, 0x6d, 0xad, 0x2b, 0x5b, 0xc9, 0xe7, 0xd4,
	0x46, 0xbc, 0xc8, 0xc0, 0x1f, 0x4e, 0xb0, 0x33, 0xbe, 0xca, 0x86, 0x76, 0x85, 0xc2, 0x22, 0xde,
	0x82, 0xaf, 0x2f, 0xda, 0xc8, 0x96, 0x56, 0x05, 0xc2, 0x65, 0xcb, 0x7b, 0x60, 0xee, 0xff, 0x60,
	0x00, 0xb3, 0xcd, 0x76, 0xb7, 0x8e, 0xfe, 0x21, 0x80, 0x5f, 0xec, 0xc5, 0xf6, 0xf5, 0x25, 0xf2,
	0x30, 0x84, 0xf9, 0xf3, 0x2e, 0x2f, 0xd6, 0xd1, 0xa4, 0xf2, 0xe9, 0x1d, 0x56, 0x3f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x57, 0xfd, 0xbc, 0x59, 0xa0, 0x01, 0x00, 0x00,
}
